"""empty message

Revision ID: 26c8943179b6
Revises: 
Create Date: 2022-03-30 18:47:38.504849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '26c8943179b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('f5_min', sa.Integer(), nullable=True),
    sa.Column('t20_min', sa.Integer(), nullable=True),
    sa.Column('s60_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_config_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('application', sa.String(length=64), nullable=True),
    sa.Column('sla_number', sa.Integer(), nullable=True),
    sa.Column('sla_description', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('level_type', sa.String(length=64), nullable=True),
    sa.Column('sla_type', sa.String(length=64), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('weightage', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Boolean(), nullable=True),
    sa.Column('circle_level_sla', sa.Boolean(), nullable=True),
    sa.Column('table_name', sa.String(length=64), nullable=True),
    sa.Column('sla_cal_condition', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('indicator', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_config_param',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('param_type', sa.String(length=64), nullable=True),
    sa.Column('param_account', sa.String(length=64), nullable=True),
    sa.Column('param_name', sa.String(length=64), nullable=True),
    sa.Column('param_value', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_data_manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('sla_date', sa.Date(), nullable=True),
    sa.Column('sla_number', sa.Integer(), nullable=True),
    sa.Column('sla_type', sa.String(length=64), nullable=True),
    sa.Column('total_request', sa.Integer(), nullable=True),
    sa.Column('within_sla_reqeust', sa.Integer(), nullable=True),
    sa.Column('sla_percentage', sa.Float(), nullable=True),
    sa.Column('sla_met', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_pending_approval',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('activity', sa.String(length=64), nullable=True),
    sa.Column('dynamic_information', mssql.JSON(), nullable=True),
    sa.Column('justification', sa.String(length=400), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('sla_user_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('email_id', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('reset_ind', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_user_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('mobile_number', sa.BigInteger(), nullable=True),
    sa.Column('email_id', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_update_date', sa.DateTime(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sla_user_role')
    op.drop_table('sla_user_query')
    op.drop_table('sla_user_management')
    op.drop_table('sla_pending_approval')
    op.drop_table('sla_data_manager')
    op.drop_table('sla_config_param')
    op.drop_table('sla_config_details')
    op.drop_table('sla')
    # ### end Alembic commands ###
